[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm run serve"

[build.nixpacks]
npmOverride = true

[build.nixpacks.node]
version = "20"

[build.nixpacks.phases.build]
cmds = [
  "npm ci",
  "npm run build",
  # 静的ファイルの確認
  "echo 'Build completed. Checking dist directory...'",
  "ls -la dist/ || echo 'dist directory not found'",
  "ls -la dist/assets/ || echo 'assets directory not found'"
]

[build.nixpacks.phases.start]
cmds = ["npm run serve"] 