[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm run serve"

[build.nixpacks]
npmOverride = true

[build.nixpacks.node]
version = "20"
