[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"

[build.nixpacks]
# 確実なFFmpegインストール
packages = ["ffmpeg", "python3Packages.yt-dlp"]

[build.nixpacks.python]
version = "3.12"

[build.nixpacks.phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[build.nixpacks.phases.build]
cmds = [
  # FFmpegを確実にPATHに追加
  "echo 'Setting up FFmpeg...'",
  "mkdir -p /usr/local/bin",
  # NixストアからFFmpegを検索して直接リンク
  "find /nix/store -name 'ffmpeg' -type f -executable 2>/dev/null | head -1 | xargs -I {} ln -sf {} /usr/local/bin/ffmpeg",
  # PATHに追加
  "echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bashrc",
  # 検証
  "ls -la /usr/local/bin/ffmpeg",
  "/usr/local/bin/ffmpeg -version 2>/dev/null | head -1 || echo 'FFmpeg setup failed'"
]

[build.nixpacks.env]
PATH = "/usr/local/bin:$PATH" 